# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fbd894d314d3103589828b443d8849f00811a6127688b2ba143eb03f6ad44535c060cad699e4e1aaf0383aff59a0dab8be076b79f417716f8a27f1e131b2bc05

test:
  secret_key_base: 748e04aa9d520ae43b5dfc75c7ce4ab076d2fefaa16c73a1b5c9f7e862066a27cc8a105fc7c0269965e511ac23df1f73ec3de8b4f3fead9986b5d7b63586d938

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
